<a href="https://colab.research.google.com/github/Mrpickles-666/project-alpha/blob/main/PI_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introdução

Como geramos um programa de computador?

No início os programadores escreviam instruções diretamente para o processador. Era um processo trabalhoso, gerava códigos enormes.

Soluções:
- Programas compilados
- Programas interpretados

![rect833-9-7.png]()
O que é Python?
- Linguagem de programação interpretada


##Instalação

Instalação do Interpretador:
- https://www.python.org/

Instalação da IDE:
- https://code.visualstudio.com/
- https://www.jetbrains.com/pycharm/

Qual a melhor IDE? Ambas são bastante populares no mercado hoje, experimente e decida qual gosta mais. A principal vantagem o VS Code é sua popularidade com outras linguagens.

##Primeiro código

In [ ]:
print('Alo mamãe')

In [ ]:
#ERRO
Print('Alo mamãe')

In [ ]:
#A cerquilha é como colocamos comentários
print('Alo mamãe')
print('Alo papai')

#Comandos básicos

In [ ]:
#variaveis numéricas
idade = 30
peso = 49.5
#variável String(texto)
nome = 'Mario' #aspas simples
endereco = "Rua dos cogumelos, 274" #aspas duplas

print('Seja bem vindo',nome,'seu "produto" será enviado para',endereco)

In [ ]:
#formas de impressão com dados
idade=30
nome="Mario"
print("Olá,",nome,"sua idade é",idade,"parabéns")
print("Olá, {} sua idade é {} parabéns".format(nome,idade))
print(f"Olá, {nome} sua idade é {idade} parabéns")

In [ ]:
#cuidados na hora do print, veja o que cada caso retorna
print(2 + 3)
print('2 + 3')
print('2' + '3')
print('Olá ' + 'Mundo')

##Operações aritméticas básicas

*   Soma
> 3+5

*   Subtração
>  8-4
*   Multiplicação
> 5*4
*   Divisão Real
> 7/2    (resultado 3.5)
* Divisão Inteira
> 7//2   (resultado 3)
* Resto de divisão
> 7 % 2  (também chamado de MOD)
*Exponenciação
> 3**2

In [ ]:
#comandos básicos aritméticos
valorA = 10+5
valorB = (80*4)-1
valorC = valorB/valorA +1
valorC = valorC**2
print('O resultado final é',valorC)

In [ ]:
#Atenção
print(10+2*3)

##Leitura do teclado

In [ ]:
nome = input("Digite seu nome: ")
print("Seja bem vindo",nome)

In [ ]:
#ERRO
idade =input("Digite sua idade:")
print("Em 2 anos você terá", idade+2)

In [ ]:
#CORRETO
idade =int(input("Digite sua idade: "))
print("Em 2 anos você terá", idade+2)

In [ ]:
#tipos possíveis
dado = input('Digite: ')
idade = int(dado) #caso seja um valor inteiro
peso = float(dado) #caso seja um valor real
nome = dado #não é necessário conversão caso seja uma string

#Exercícios de comandos básicos

1- Leia três notas de um aluno (0~10) e informe a média:

In [ ]:
print("Informe suas 3 notas da prova")
n1 = float(input("Digite nota 1: "))
n2 = float(input("Digite nota 2: "))
n3 = float(input("Digite nota 3: "))
media = (n1 + n2 + n3)/3
print('O resultado é',media)
#print('O resultado é',(n1 + n2 + n3)/3)

2- Agora calcule a média ponderada considerando os pesos 1 3 5 nas três provas

In [ ]:
n1 = float(input("Digite nota 1: "))
n2 = float(input("Digite nota 2: "))
n3 = float(input("Digite nota 3: "))
mediaPonderada = (n1*1 + n2* 3 + n3*5)/9
print("Sua nota pela média Ponderada é:",round(mediaPonderada,2))
print("Sua nota pela média Ponderada é: {:.2f}".format(mediaPonderada))
print(f"Sua nota pela média Ponderada é: {mediaPonderada:.2f}")

3- Imprima a área de um círculo

In [ ]:
import math
raio= 10
area = math.pi * raio**2
print('A área do circulo é',area)
#math.sqrt pode ser usado para raiz quadrada, ou também (valor ** 0.5)

4- Imprima um F feito de #
#####

#
###

#

#

In [ ]:
print('####\n#\n#\n###\n#\n#')
print()
print("####")
print("#")
print("#")
print("###")
print("#")
print("#")
print()
print("#" * 4, end ="")
print("\n#" * 2)
print("#" * 3, end ="")
print("\n#" * 3, )

5- Pergunte ao usuário quantos anos, meses e dias ele viveu. E então responda o total de dias vividos por ele. Para simplificar o cálculo assuma todo o ano com 365 dias e todo o mês com 30 dias.

In [ ]:
anos = int(input("Informe anos"))
meses = int(input("Informe meses"))
dias = int(input("Informe dias"))
total = anos*365 + meses*30 + dias;
print("Sua idade em dias é",total)

6- Assuma que pessoa efetuou um emprestimo, e que a multa por dia de atraso do empréstimo é de 2%. Pergunto ao usuário o total emprestado, o total de dias e informe o valor final que deve ser pago. Utilize juros simples

In [ ]:
emprestimo = float(input("Digite o valor do emprestimo: "))
dias = int(input("Digite o total de dias de atraso: "))
multaDiaria = emprestimo * (2/100)
total = emprestimo + (dias*multaDiaria)
print(f"O total que deve ser pago é de R$ {total:.2f}")

#Desvio lógico

Desvio condicional simples: Quando temos uma situação em que dependendo de determinada condição um código pode ou não executar

In [ ]:
idade = int(input('Digite sua idade: '))
#SE idade menor que 18, executa o print
if idade < 18:
  print('Acesso bloqueado') #repare no espaço(TABulação) antes.
print('Fim do programa') #executa sempre

Chamamos de identação o espaçamento de cada linha de código. A identação marca quais comando fazem parte do IF

In [ ]:
#print associado ao IF
if idade < 18:
  print('Acesso bloqueado')

#ERRO falta identação
if idade< 18:
print('Acesso bloqueado')

#Dois prints associadas ao if, terceiro print, independente
if idade<18:
  print('Acesso')
  print('Bloqueado')
print('Fim')

Mais uma vez a identação é importante, repare que o código associado ao IF e ao ELSE devem ser identados, mas o comando ELSE e IF devem estar no mesmo nível

##Operadores relacionais

In [ ]:
a=10
b=9
print(a >  b) # a maior que b ?
print(a >= b) # a maior ou igual a b?
print(a <  b) # a menor que b?
print(a <= b) # a menor ou igual a b?
print(a == b) # a é igual a b?
print(a != b) # a e diferente de b?

##Operadores lógicos

In [ ]:
a=True
b=False
c=True
print(a and b) # a E b são verdade?
print(a or  b) # a OU b são verdade?
print(not   a) # o inverso de a é verdade?

print(a and b and c) #todos devem ser verdadeiro para essa avaliação ser verdade
print(a or b or c) #ao menos uma deve ser verdade para a avaliação ser verdade

##Outros desvios

Desvio condicional composto: Quando temos uma situação em que dependendo da condição um código OU outro executa

In [ ]:
num = int(input("Digite um valor: "))

#resto da divisão por 2 igual a 0, ou seja divisível por 2(par)
if num % 2 == 0 :
  print("Número par")
else: #executa se a condição falhar
  print("Número ímpar")

print("Fim do programa")

Condicional aninhada

In [ ]:
x = int(input("Digite um valor: "))
y = int (input("Digite outro valor: "))
if x > y:
  print("X é maior")
else:
  if y > x:
    print("Y é maior")
  else:
    print("X e Y iguais")


print("Fim do programa")

Condicional múltipla escolha

In [ ]:
x = int(input("Digite um valor: "))
y = int (input("Digite outro valor: "))
if x > y:
  print("X é maior")
elif y > x:
  print("Y é maior")
else:
  print("X e Y iguais")

print("Fim do programa")

In [ ]:
# IMPORTANTE Fique atento a ordem das verificações!
nome = input ("Digite seu nome: ")
idade = int(input("Digite sua idade: "))


if nome =="Mario":
  print("Parabéns por se chamar Mario")
elif idade < 18:
  print("Você NÃO se chama Mario, lamento. E você é menor de idade")
elif idade % 2 == 0 :
  print("Você NÃO se chama Mario, sua idade NÃO é menor que 18, porém sua idade é par")
else:
  print("Você NÃO se chama Mario e NÃO tem menos que 18 e NÃO tem idade par")

#Exercícios de desvio condicional

1- Leim 3 valores float representando notas em uma matéria: aprovado se as 3 notas for maior igual que 7, senão de reprovado.

In [ ]:
n1 = float(input('primeira nota?'))
n2 = float(input('segunda nota?'))
n3 = float(input('terceira nota?'))

if n1>=7 and n2>=7 and n3>=7:
  print('você está aprovado')
else:
  print('você está reprovado')

2- Dados os itens e valores abaixo, perguntar qual item e quantidade de itens e devolver o valor final.

Maça 2.3

Laranja 3.6  

Banana 1.85

In [ ]:
print('Frutas \n1-Maçã','\n2-Laranja','\n3-Banana')
produto = int(input('Qual sua escolha? '))
qtd = int(input('Quantas unidades? '))
valorMaca= 2.3
valorLaranja = 3.6
valorBanana = 1.85
if produto == 1:
  valorFinal = qtd * valorMaca
  print(f'O valor final é de : {valorFinal:.2f}')
elif produto == 2:
  valorFinal = qtd *valorLaranja
  print(f'O valor final é de : {valorFinal:.2f}')
elif produto == 3:
  valorFinal = qtd *valorBanana
  print(f'O valor final é de : {valorFinal:.2f}')
else:
  print('Produto inválido')

3- Leia login e senha de um usuário e informe se ele acertou

In [ ]:
login = input("Login: ")
senha = input("Senha: ")
if login=="mario" and senha=="peachS2":
  print("Login com sucesso")
else:
  print("Acesso negado, tente novamente")

4- Leia 3 números e diga qual o maior

In [ ]:
num1 = int(input("Digite um numero: "))
num2 = int(input("Digite outro numero: "))
num3 = int(input("Digite um ultimo numero: "))
if num1 == num2 and num1 == num3:
  print("Todos iguais")
if num1>=num2 and num1>=num3:
  print("Maior numero é o primeiro ", num1)
elif num2>=num1 and num2>=num3:
  print("o maior numero foi o segundo ", num2)
elif num3>=num1 and num3>=num1:
  print("o maior numero é o terceiro ",num3)

5- Leia 3 notas e calcule a média e informe se está aprovado de final ou reprovado

In [ ]:
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
media = (nota1+nota2+nota3)/3
print("Sua média é: ",media)
if media >=7 :
  print("Aprovado")
elif media>=4 :
  print("Final")
else:
  print("Reprovado")

6- Expandir o exercício e verificar também a quantidade de faltas (8 ou mais faltas reprovado por falta)

In [ ]:
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
faltas = int(input("Digite a quantidade de faltas: "))
media = (nota1+nota2+nota3)/3
print("Sua média é: ",media)
if faltas >= 8:
  print("Reprovado por faltas")
elif media >=7 :
  print("Aprovado")
elif media>=4 :
  print("Final")
else:
  print("Reprovado por nota")

7- Calculo de ano bissexto

São bissextos todos os anos múltiplos de 400, p.ex.: 1600, 2000, 2400, 2800...


São bissextos todos os múltiplos de 4, exceto se for múltiplo de 100 mas não de 400, p.ex.: 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028...



Não são bissextos todos os demais anos.

In [ ]:
ano = int(input('Digite um ano: '))

if (ano % 4 == 0 and ano % 100 != 0) or ano % 400 == 0:
    print('Ano bissexto.')
else:
    print('Não é um ano bissexto.')

8- Leia um carácter do teclado e diga se é um número, letra ou símbolo.

In [ ]:
caracter = input('Digite um carácter: ')
ascii= ord(caracter)
if  (ascii >= 65 and ascii <= 90) or (ascii > 97 and ascii <= 122) :
  print('É uma letra ')
elif ascii >=48 and ascii <= 57:
  print('É um número')
else:
  print('É um símbolo')

9- Leia dois números e diga se são múltiplos entre si

In [ ]:
n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
if n1 % n2 == 0 or n2 % n1 == 0:
  print('Esses números são múltiplos')
else:
  print('Esses números não são múltiplos')

#Estruturas de Repetição

Principal comando de repetição: "while"
(enquanto). Executa o código enquanto a condição for verdadeira

In [ ]:
dedos=0 #contador
while i < 5 :
  print(f"Bom dia numero {dedos}")
  dedos= dedos + 1 #IMPORTANTE, caso esqueça entra em loop infinito

Loop pode começar e terminar em quaisquer valores.

In [ ]:
inicial = int(input("Digite onde deseja começar o loop "))
final = int (input("Digite onde deseja finalizar o loop "))
i = inicial
while i <=final :
  print("Valor:",i)
  i+=1 # i= i + 1

print('fim do código')

Acumulador de valores

In [ ]:
inicial = int(input("Digite onde deseja começar o loop "))
final = int (input("Digite onde deseja finalizar o loop "))
i = inicial
soma=0
while i <=final : # 6
  print("Valor:",i)
  soma += i #soma= soma+i # 0 +3 => 3; 3 + 4 => 7; 7+5 => 12; 12 + 6 => 18;
  i+=1   #i=i+1  #3+1 => 4; 4+1 => 5; 5+1 => 6; 6+1 => 7;

print('Soma:',soma)
print('fim do código')

Decremental

In [ ]:
i= 10
while i >=1:
  print("Contagem:",i)
  i-=1 #i=i-1

Validação, valor positivo

In [ ]:
#validacao
#validar que o valor é positivo
num = int(input("Digite um valor positivo "))
while num <=0 :
  num = int(input("Digite um valor positivo "))

print("O valor positivo digitado foi:",num)

Validação, valor com 3 dígitos

In [ ]:
#validacao número de 3 dígitos
num = int(input("Digite um valor de 3 dígitos "))
while num<100 or num>999 :
  num = int(input("Digite um valor de 3 dígitos "))

print("O valor positivo digitado foi:",num)

Combinando while e if

In [ ]:
i=0
while i<=100 :
  if i % 5 == 0 :
    print("Multiplo de 5:",i)
  i+=1

Exemplo - Fatorial

In [ ]:
#Fatorial
#      5!  => 1 * 2 * 3 * 4 * 5 => 120
fat=1
i=1
num = int(input("Digite um valor para o fatorial: "))  #num = 4
while i <= num :
  fat *= i  #fat= fat*i                                 fat # 1; 1*1 => 1; 1 * 2 => 2; 2 * 3 => 6; 6* 4=> 24;
  i +=1     #i= i+1                                       i # 1  1+1 => 2;  2 +1 => 3; 3 + 1 => 4; 4+ 1=> 5
print("Fatorial:",fat)

In [ ]:
#alternativo
import math

resposta = math.factorial(4)
print(resposta)

Exemplo - Faça a soma dos 20 primeiros elementos de uma PA de razão 3 e cujo primeiro elemento seja fornecido pelo usuário

In [ ]:
#Soma PA 20 elementos razao 3
qtd=20
razao =3
inicial = int(input("Digite o valor inicial da PA"))
i=0
resp=0
#10 + 13 + 16 + 19 + 22 + 25
#                         10 + 3*5
while i < qtd :
  resp +=  inicial + (razao * i)
  i+=1

print("Resposta: ", resp)

Comando for

In [ ]:
listaAlunos = ["mario","luigi","yoshi"]
for aluno in listaAlunos :
  print("Bem vindo", aluno)

range

In [ ]:
for i in range(10) :
  print(i)

In [ ]:
for i in range(5,10):
  print(i)

In [ ]:
for i in range(1,50,2):
  print(i)

In [ ]:
for i in range(10, 0, -1):
  print(i)

In [ ]:
#1-10 while
i=1
while i <=10 :
  print(i)
  i=i+1

#1-10 for
for i in range(1,11) :
  print (i)

# Exercícios de Estruturas de Repetição

Exercício 1- Faça um programa que descubra qual a soma dos 50 primeiros números.

>Depois. Soma apenas dos impares.

In [ ]:
i=1
soma=0
while i <=50 :
  soma = soma + i
  i+=1
print(soma)

In [ ]:
i=1
soma=0
while i <=50 :
  soma = soma + i
  i+=2
print(soma)

In [ ]:
#verificando se o valor é ímpar
i=1
soma=0
while i <=50 :
  if i % 2 != 0 :
    soma = soma + i
  i+=1
print(soma)

Exercício 2 - Um programa que peça a um usuário digite seu nome e um número inteiro e imprima o nome daquele usuário o número de vezes informado.

In [ ]:
qtd = int(input("Digite a qtd: "))
nome = input("Digite o seu nome: ")

for i in range(qtd):
  print(nome)

In [ ]:
qtd = int(input("Digite a qtd: "))
nome = input("Digite o seu nome: ")
i=0
while i < qtd :
  print(nome)
  i+=1

In [ ]:
nome = input('Digite seu nome')
numero = int(input('Digite um número inteiro'))
print (  (nome +"\n") * numero)

Exercício 3- Leônidas é constantemente questionado sobre quantos soldados seus trezentos espartanos irão enfrentar.
Ajude Leônidas fazendo um pequeno jogo de adivinhação em que o jogador deve dar um palpite, caso seja abaixo ou acima do valor correto imprima mensagens adequadas informando o fato.  (Valor correto deve ser: 10000)

In [ ]:
palpite = int(input("Digite um palpite"))
soldados =10000
while palpite != soldados :
  if palpite > soldados:
    print("Um pouco menos")
  else:
    print("Um pouco mais")
  palpite = int(input("Digite um palpite"))

print("Parabéns, você acertou")

Números aleatórios

import random
valorDado = random.randint(1,6)
temperatura = random.uniform(35.5, 41.9)

In [ ]:
import random

palpite = int(input("Digite um palpite"))
soldados =random.randint(8000,12000)
while palpite != soldados :
  if palpite > soldados:
    print("Um pouco menos")
  else:
    print("Um pouco mais")
  palpite = int(input("Digite um palpite"))

print("Parabéns, você acertou")

Exercício 4- Faça um programa que leia valores do teclado até o usuário digitar 0.
No momento que o usuário digitar 0, o programa deve informar qual a média dos valores digitados.

O valor 0 não deve ser incluído nesse calculo de média.

In [ ]:
num = float(input("Digite um número: "))
soma=0
qtd=0
while num:
  soma+=num
  qtd+=1
  num = float(input("Digite um número: "))
media = soma/qtd
print("O resultado é {:.2}".format(media))

“Truthy” e “Falsey”
- Falsey:
> Valor numérico 0 (zero)
> String vazia   ' '    " "
> Coleções vazias  (listas, tuplas, dicionários, ...)
> False
- Truthy:
> Valor numérico diferente de  0 (zero)
> String não vazia
> Coleções não vazias
> True

Exercício 5- Faça um programa que leia valores do teclado até o usuário digitar 0.
No momento que o usuário digitar 0, o programa deve informar qual foi o maior valor digitado.

In [ ]:
num = float(input("Digite um valor: "))
maximo = num
while num :
  if num > maximo :
    maximo = num
  num = float(input("Digite um valor: "))

print("Maximo: {}.".format(maximo))

Exercício 6- Faça um programa que repetidamente pergunte a idade e o gênero para o usuário. E para cada resposta o programa deve responder imprimir a mensagem:


>“Boa noite rapaz.” caso gênero masculino e idade < 18

> “Boa noite senhor.” caso gênero masculino e idade >= 18

> “Boa noite moça.” caso gênero feminino e idade < 18

> “Boa noite senhora.” caso gênero feminino e idade >=18

Quando o usuário digitar 0 no campo idade o programa deve encerrar.

In [ ]:
idade = int(input("Digite sua idade: "))

while idade :
  genero = input("Digite o seu gênero: ").lower()[0]
  if idade <18 :
    if genero == "m" :
      print("Bom dia rapaz")
    elif genero == "f":
      print("Bom dia moça")
  else:
    if genero == "m" :
      print("Bom dia senhor")
    elif genero == "f":
      print("Bom dia senhora")
  idade = int(input("Digite sua idade: "))

Exercício 7- Faça um código que imprima os números de 1 até 50 em ordem crescente e depois em ordem decrescente. Seu código deve pular o número 37.

>Resultado:

>1 2 3 4 … 35 36 38 39 … 48 49 50 50 49 48 … 39 38 36 35…. 3 2 1

In [ ]:
for i in range(1,51) :
  if i==37 :
    continue
  print(i)
for i in range(50,0,-1) :
  if i==37 :
    continue
  print(i)

Exercício 8- Faça um programa que imprima a tabulada do 1 ao 10

In [ ]:
for i in range(1,11) :
  for j in range(1,11) :
    print("{} x {} = {}".format(i,j,i*j) )
  print('--------------')

Exercício 9- Leia um número do teclado e diga se o mesmo é primo

In [ ]:
numero = int(input("Digite um número: "))

primo=True
for i in range(2, numero):
  if numero%i == 0:
    primo=False
    break

if primo:
  print("O número {} é primo".format(numero))
else:
  print("O número {} não é primo".format(numero))

Exercício 10- Fazer um programa que diga quais números são primos ou não do 2 até o 37

In [ ]:
#numero = int(input("Digite um número: "))
for numero in range(2,38) :
  primo=True
  for i in range(2, numero):
    if numero%i == 0:
      primo=False
      break

  if primo:
    print("O número {} é primo".format(numero))
  else:
    print("O número {} não é primo".format(numero))

#Funções

Funções são uma forma de dar apelidos para trechos de código. Serve para melhorar sua organização e diminuir a reescrita de trechos de códigos similares

In [ ]:
print('|',"_"*18,"|")
print('|',"_"*18,"|")
print('          MENU')
print('|',"_"*18,"|")
print('|',"_"*18,"|")

In [ ]:
def darDestaque() :
  print('||',"_"*18,"||")
  print('||',"_"*18,"||")


darDestaque()
print('          MENU')
darDestaque()

Funções com parâmetro

In [ ]:
def darDestaque(mensagem) :
  print('||',"_"*18,"||")
  print('||',"_"*18,"||")
  print('          ',mensagem)
  print('||',"_"*18,"||")
  print('||',"_"*18,"||")


darDestaque('Olá')
darDestaque('Menu')

In [ ]:
def borda(texto) :
  tamanho = len(texto)
  print('+','-'*tamanho,'+')
  print('|',texto,'|')
  print('+','-'*tamanho,'+')

borda('Menu')
borda('Lógica de Programação e Algoritmos')
borda('')

Contexto das funções

In [ ]:
numeroA=12 #global todas as funções conseguem ler apenas

def func():
  #global numero #permite que a variavel global seja modificada
  numero=6
  #global outroNumero #torna a variavel global
  outroNumero=10
  print('func numero:',numero)

func()
print('principal numero:',numero)
#print('principal outroNumero:',outroNumero) # ERRO, sem acesso a essa variável

Funções com múltiplos parâmetros

In [ ]:
def somar3(x,y,z) :
  res= x+y+z
  print(res)

somar3(3,4,5)
somar3(30,40,50)
somar3(20,30)

Parâmetros opcionais

In [ ]:
def somar3(x=0,y=0,z=0) :
  res= x+y+z
  print(res)
somar3(3,4,5)
somar3(3,4)
somar3(3)
somar3()
somar3(0,0,2)

Função com retorno

In [ ]:
def somar(x=0,y=0,z=0) :
  res= x+y+z
  return res

resposta = somar(2,3,7)  # resposta = 12
resposta+=1
print(resposta)

print("Resultado é:",somar(60,50)) # print("Resultado é:",110)

Função como parâmetro e lambda

In [ ]:
def par(num) :
  return num %2 == 0

def impar(num) :
  return not par(num)

def imprime_com_condicao(numero, funcao) :
  if funcao(numero) :
    print(numero)

imprime_com_condicao(1,impar)
imprime_com_condicao(2,par)
imprime_com_condicao(3,impar)
imprime_com_condicao(4,impar)
imprime_com_condicao(5,par)
imprime_com_condicao(0,lambda x : x>5)

#Exercícios de Funções

Exercício 1- Crie uma função que retorne o maior de 3 números passados por parâmetro

In [ ]:
def maior3(x,y,z) :
  if x >= y and x >= z :
    return x
  elif y >= x and y >=z :
    return y
  else:
    return z

val1 = float(input("Digite um numero: "))
val2 = float(input("Digite um numero: "))
val3 = float(input("Digite um numero: "))
resultado = maior3(val1,val2,val3)
print(resultado)

Exercício 2- Utilize a função anterior para descobrir o maior dentre 9 números.

In [ ]:
def maior3(x=0,y=0,z=0) :
  if x >= y and x >= z :
    return x
  elif y >= x and y >=z :
    return y
  else:
    return z

maioral1 = maior3(60,70,20)
maioral2 = maior3(80,10)
maioral3 = maior3(20,90,80)
maiorTodos = maior3(maioral1,maioral2,maioral3)

print('Maior de todos: ',maiorTodos)

Exercício 3- Faça uma função chamada quadrado(lado) que recebe como parâmetro um número representando a medida do lado de um quadrado e imprima 3 valores:
>Área  (lado * lado)

>perímetro  (4 * lado)

>tamanho da diagonal ( lado * √ 2)

In [ ]:
import math

def quadrado(lado) :
  area = lado*lado
  perimetro= 4*lado
  diagonal = math.sqrt(2)*lado
  print("Area:",area)
  print("Perimetro:",perimetro)
  print("Diagonal",diagonal)

quadrado(7)
quadrado(8)

Exercício 4- Faça uma função que recebe um número como parâmetro e retorna se o valor é positivo ou não retornando: True ou False

In [ ]:
def ehPositivo(numero):
  #return numero>0
  if numero>0:
    return True
  else:
    return False

print(ehPositivo(5))
print(ehPositivo(0))
print(ehPositivo(-3))

Exercício 5- Escreva uma função que imprima quantas letras em uma string recebida por parâmetro são maiúscula e quantas são minúsculas.

In [ ]:
totalMaiusculas=0
totalMinusculas=0
mensagem = input("Digite sua mensagem: ")
#loop cada letra na string
for caractere in mensagem :
  if caractere.isupper(): #verifica se é maiúscula
    totalMaiusculas+=1
  elif caractere.islower(): #verifica se é minúscula
    totalMinusculas+=1
print("Total Maiusculas:",totalMaiusculas)
print("Total Minusculas:",totalMinusculas)

Exercício 6- Faça uma função que recebe o um raio(R) e retorne o volume de uma esfera. Leitura e impressão de dados deve ser feita fora da função.

O volume de uma esfera é fornecido pela fórmula V = (4π/3)  * R3

In [ ]:
import math

def calcularVolume(raio) :
  volume = (4* math.pi/3) * raio**3
  return volume

valorRaio = float(input("Digite o raio:"))
resultado = calcularVolume(valorRaio)

print("Resposta: ",resultado)

Exercício 7- Crie uma função que dado um número inteiro como entrada, retorna o número de dígitos que ele possui.

In [ ]:
def cont(numero) :
  #str: transforma numero em string
  #len: retorna o tamanho da string
   return len(str(numero))

def contMat (num) :
  contador=0
  while num!=0 :
    num= num//10
    contador+=1
  return contador


num = int(input("Digite um número: "))
print("O número {} possui: {} dígitos.".format(num, cont(num) ))
print("O número {} possui: {} dígitos.".format(num, contMat(num) ))

Exercício 8- Crie uma função que ao receber uma base e um expoente retorna a potência

In [ ]:
def potencia (base,expoente) :
  resp=1
  #multiplicacao da base tantas vezes quanto o expoente
  for i in range(expoente):
    resp *= base  # resp = resp * base
  return resp


print(potencia(2,10))

Exercício 9- Crie uma função chamada compressor. Que recebe 3 números inteiros de 1 dígito e retorna 1 número com 3 dígitos.

>Exemplo:  compressor(5,6,7)  deve retornar quinhentos e sessenta e sete.

In [ ]:
def compressaoMat(d1,d2,d3) :
  return d1*100 + d2*10 + d3

def compressao(d1,d2,d3) :
  resposta = str(d1) + str(d2) + str(d3)
  return int(resposta)

resultado = compressao(5,6,7)
print("O resultado é:",resultado)
resultado = compressaoMat(5,6,7)
print("O resultado é:",resultado)

Exercício 10- Imprima qual o somatório de todos os números pares e ímpares de uma sequência numérica digitada pelo usuário.

>O usuário deve digitar um inteiro N
E depois a sequência de N números

In [ ]:
n = int(input('Qual o tamanho da sequência?'))
somaPar=0
somaImpar=0
for i in range(n):
  num = input('Número: ')
  if num %2==0: #par
    somaPar+=num
  else:
    somaImpar+=num
print('Soma Par:',somaPar)
print('Soma Impar:',somaImpar)

#Tuplas e Listas

- Coleção de valores
- Pode possuir diferentes tipos de dados
- **Tuplas:** Não aceita ser modificado
- **Listas:** Podem ser modificadas

###Tuplas

Acesso por índices

In [ ]:
#indice positivo   0    1     2     3     4     5
#indice negativo  -1   -2    -3    -4    -5    -6
megaSena =        (8,  20,   37,   40,   44,   51)

print(megaSena[0])
print(megaSena[1])
print(megaSena[4])
print(megaSena[-1])
print(megaSena[-3])

megaSena[4]= 45 #ERRO, tupla não pode ser modificada

Acessar elementos em loop

In [ ]:
megaSena = (8, 20, 37, 40, 44, 51)
for numero in megaSena :
  print(numero)

Acessando elementos em loop por indice

In [ ]:
tam = len(megaSena)#len: retorna o tamanho da coleção
for i in range(tam) :
  print("Numero sorteado:", megaSena[i]  )

In [ ]:
#enumerate i=indice v=valor
for pos,valor in enumerate(megaSena) :
  print( "Na posição {} tem o valor {}".format(pos,valor))

Fatiamento, ao invés de selecionar um único item, mas sim trechos. Funciona tanto com tuplas, listas e strings

In [ ]:
s1 = 'Super Mario'
print(s1[0:5]) #Índices de 0 até 4
print(s1[:5])  #Índices do início(0) até 4
print(s1[6:11])#Índices de 6 até 10
print(s1[6:])  #Índices de 6 até o final(10)
#Índices negativos também podem ser utilizados
print(s1[6:-1])#Índices de 6 até o -1 (10)

É possível configurar o fatiamento em passos

In [ ]:
print(s1[0:11:3]) #Índices de 0 até 10, espaçado de 1 a cada 3
print(s1[::2]) #Índices do inicio (0) até fim(10), espaçado de 1 a cada 2
print(s1[0:11:-1]) #Índices de 0 até 10, espaçado de -1 em -1 ou seja fica a string ao contrário
print(s1[::-1]) #Índices do início(0) até o fim (10), espaçado de -1 em -1 ou seja fica a string ao contrário

Concatenação de tuplas

In [ ]:
megaSena = (8, 20, 37, 40, 44, 51)
extra = (3, 56)
megaSenaTotal = megaSena + extra
print(megaSenaTotal)

#ordem
megaSenaTotal = extra + megaSena
print(megaSenaTotal)

Desempacotando de parâmetros em função:

In [ ]:
def somar(*numeros):
  somatorio =0
  for num in numeros :
    somatorio+= num
  return somatorio

resultado = somar(1,2)
print('Resultado: {}'.format(resultado))

resultado = somar(1,2,3,4,5,6,7,8,9)
print('Resultado: {}'.format(resultado))

###Lista

Listas são semelhantes as tuplas, porém permitem manipulações. Remover, inserir especificamente e alterar elementos.

In [ ]:
alunos = ['Mario','Luigi','Yoshi','Toad']

alunos[0] = 'Super Mario'
print(alunos)

#remove partindo do indice
del alunos[1]

print(alunos)

#removendo partindo do conteúdo
alunos.remove('Yoshi')
print(alunos)

In [ ]:
alunos = ['Mario','Luigi','Yoshi','Toad']
#insere posição específica
alunos.insert(2,'Peach')
#insere ao final
alunos.append('Bowser')
print(alunos)

Referências

In [ ]:
#Referencia
x = [10,20,30,40,50]
#y não é uma cópia mas sim referencia do próprio x
y = x
x[0]=100

print(x)
print(y)

Cópia

In [ ]:
x = [10,20,30,40,50]
y = x[:]
#nesse caso o y é uma cópia
x[0]=100

print(x)
print(y)

Strings e listas

In [ ]:
alunos = ['Mario','Luigi','Yoshi','Toad']
print( alunos[0][1] )#Acessando a string na posição [0], e o caracter na posição [1]
print( alunos[2][3]  )#Acessando a string na posição [2], e o caracter na posição [3]

#loop que acessa cada string e cada letra de cada string
for aluno in alunos :
  for letra in aluno  :
    print(letra)
  print()

In [ ]:
#contar letras a dentro das palavras de uma lista
alunos = ['Mario','Luigi','Yoshi','Toad']
contador=0
for aluno in alunos :
  for letra in aluno  :
    if letra == 'a':
      contador+=1

print('Na lista existem {} letras a'.format(contador))

Exemplo, criando uma lista de mercado

In [ ]:
#criando uma lista vazia para receber as informações de cada item
item = []
#criando uma lista vazia para receber os items
mercado = []

#loop repetindo 3 vezes
for i in range(3) :
  item.append(  input('Digite o nome do item: ')   )
  item.append( int(input('Digite a quantidade de itens: ')))
  item.append( float(input('Digite o valor: ')))
  mercado.append( item[:] )#anexando uma cópia do item todo na lista mercado
  item.clear() #esvazia a lista item
print(mercado)

In [ ]:
#outra forma mais concisa de escrever o mesmo código
mercado = []

for i in range(3) :
   nome = input('Digite o nome do item: ')
   qtd = int(input('Digite a quantidade de itens: '))
   valor = float(input('Digite o valor: '))
   mercado.append(   [nome,qtd,valor]    )

print(mercado)

In [ ]:
#exemplo de como imprimir os dados
mercado = [['Cebola', 2, 0.58], ['Tomate', 3, 0.48], ['Alface', 1, 2.0]]

soma=0

print('Lista de compras:')
print('-'*20)
print('item | quantidade | valor unitário | valor total')
for item in mercado:
  print('{} | {} | {} | {}'.format(item[0],   item[1],  item[2],  item[1]*item[2]  ))
  soma += item[1]*item[2]

print('-'*20)
print('Valor final:',soma)

#Exercícios Tuplas e Listas

Exercício 1- Crie um programa que dada uma lista de números diga quantos são positivos, negativos e quantos valem zero.

In [ ]:
#ler os dados
listaNumeros = []
total = int(input("Digite quantos valores terá a sequência: "))
for i in range(total) :
  listaNumeros.append(  int(input('Digite o próximo valor: '))      )

#forma alternativa de ler os dados
'''
listaNumeros= []
valor = input("Digite uma sequência de números termina em 'fim' ")
while valor != 'fim' :
  listaNumeros.append( int(valor) )
  valor = input("")
'''

contPositivos = 0
contNegativos = 0
contZero = 0
#passa por todos os items, e incrementa o contador devido
for num in listaNumeros:
   if (num < 0):
     contNegativos += 1
   elif (num >0):
     contPositivos += 1
   else:
     contZero += 1
print(contPositivos, contNegativos, contZero)

Exercício 2- Crie um programa que diga qual é o maior e o menor valor de uma lista de números

In [ ]:
listaNum = [3,-5,8,9,-1,-9]
#define o primeiro valor como maior e menor
maiorNum = listaNum [0]
menorNum = listaNum [0]

#for each
for num in listaNum:
  if num > maiorNum :
    maiorNum = num
  elif num < menorNum :
    menorNum = num
print("O maior número é {} e o menor número é {}".format(maiorNum,menorNum))

In [ ]:
#forma alternativa
listaNum = [3,-5,8,9,-1,-9]

print( max(listaNum)   )

print( min(listaNum)   )

print( sum(listaNum)   )

Exercício 3- Escreva uma função que recebe uma lista. Substitua todos os valores nulos (0) da lista por 1.

In [ ]:
def substitui (lista) :
  tam = len(lista)
  for i in range(tam):
    if lista[i] == 0:
      lista[i] = 1

minhaLista = [1,1,0,0,1,1]
substitui(minhaLista)
print(minhaLista)

Exercício 4- Dada uma sequência de N nomes, imprimi-la na ordem inversa à da leitura.

In [ ]:
listaNomes =[]

nome = input("Digite um nome ")
while nome != 'sair' :
  listaNomes.append(nome)
  nome = input("Digite um nome ")
print("Lista ordem normal: ")
print(listaNomes)

#função que reverte listas
listaNomes.reverse()

print(listaNomes)

Exercício 5- Crie uma lista de 10 posições para simular 10 pessoas. Preencha cada posição da lista arbitrariamente com números entre 1 e 12 para indicar o mês de aniversário. Indique quantas pessoas fizeram aniversário em cada mês

In [ ]:
listaMes = [3,9,12,5,8,9,3,2,11,2,11]


for mes in range(1,13):
  contagem=0
  for aniversario in listaMes :
    if mes == aniversario:
      contagem+=1
  print('No mês {} tivemos {} aniversários.'.format(mes,contagem))

Exercício 6- Leia uma string e um número N.
Imprima as N primeiras letras do nome digitado.  
Caso N seja maior do que o tamanho do nome imprima uma mensagem de erro e encerre o programa sem fazer nada

In [ ]:
nome = input("Digite um nome: ")
N = int(input('Digite uma qtd de letras: '))

if N > len(nome) :
  print('O nome não possui tantas letras assim.')
else:
  for i in range(N) :
    print(nome[i],end='')

#Conjuntos e Dicionários

Conjunto é uma estrutura de dados simplificada, não aceita repetição, não existe posição. os elementos estão dentro do grupo ou não estão, replica os conceitos de grupo da matemática

In [ ]:
#parentes tuplas (10,20,30)
#colchetes listas [10,20,30]
#chaves conjuntos {10,20,30}
#1-10
pares = {2,4,6,8,10}
impares = {1,3,5,7,9}
primos = {2,3,5,7}
composto = {4,6,8,9}

#unir conjuntos de pares e impares
pares.union(impares)

#intersecção dos conjuntos dos pares com primos
pares.intersection(primos)

#verificar se está
if 7 in primos :
#verificar se não está em um grupo
if not 8 in primos

Dicionário é uma estrutura de dados muito importante dentro do Python, é dividida em chaves e valores, cada chave associada a um valor. podem possuir tipos diversos

In [ ]:
jogo = { 'Nome':'Super Mario', 'Desenvolvedora':'Nintendo', 'Ano': 1990 }

jogo["Genero"] = 'Aventura'
print(jogo)

principais elementos keys (chaves) values(valores)

In [ ]:
jogo.keys()

In [ ]:
jogo.values()

In [ ]:
jogo.items()

In [ ]:
listaJogos = []

jogo1 = { 'Nome':'Super Mario', 'videogame':'SNES', 'Ano': 1990 }
jogo2 = { 'Nome':'Mario Kart 64', 'videogame':'N64', 'Ano': 1998 }
jogo3 = { 'Nome':'Pokemon Yellow', 'videogame':'GameBoy', 'Ano': 1999 }

listaJogos = [jogo1,jogo2,jogo3]

#print(listaJogos)

print(listaJogos[1]['Nome'])

Adicionar/modificar dicionario com método update

In [ ]:
jogo = { 'Nome':'Super Mario', 'Desenvolvedora':'Nintendo', 'Ano': 1990 }

jogo.update({'Nome':'Mario Kart', 'Gênero':'Corrida', 'Ano':1992})
print(jogo)

Dicionario com uma lista.

In [ ]:
turma ={ 'alunos':['mario','luigi','yoshi'], 'professores':['Luciane','Leonardo']   }
#no dicionário turma está acessando a lista alunos na posição 2
print(turma['alunos'][2])

#Exercícios de Conjuntos e Dicionários

Exercício 1- Crie um dicionário das duas listas abaixo
>chaves = ['Dez', 'Vinte', 'Trinta']

>valores = [10, 20, 30]

In [ ]:
#gerar um dicionario com as listas
chaves = ['Dez', 'Vinte', 'Trinta']
valores = [10, 20, 30]

meuDicionario={}

tam= len(chaves)

for i in range(tam) :
  meuDicionario[ chaves[i] ] = valores[i]

listaChaves = list(meuDicionario.keys())

print(listaChaves)
for item in listaChaves:
  print(item)

In [ ]:
#solução alternativa 1

chaves = ['Dez', 'Vinte', 'Trinta']
valores = [10, 20, 30]

meuDicionario = dict( zip(chaves,valores) )

print(meuDicionario)

In [ ]:
#solução alternativa 2
lista = [10,20,30,40]
dicionario = {'nome':'Mario', 'idade':30,'curso':'ADS'}


listaCombinada = lista + list(dicionario.items())

print(listaCombinada)

Exercício 2- Faça uma fusão dos dois dicionários abaixo:

>dict1 = {'Dez': 10, 'Vinte': 20, 'Trinta': 30}

>dict2 = {'Trinta': 30, 'Quarenta': 40, 'Cinquenta': 50}

In [ ]:
dict1 = {'Dez': 10, 'Vinte': 20, 'Trinta': 30}
dict2 = {'Trinta': 30, 'Quarenta': 40, 'Cinquenta': 50}

dict3 = dict1.copy()

for chave,valor in dict2.items() :
  dict3[chave]=valor

print(dict3)

In [ ]:
#solução alternativa
dict1 = {'Dez': 10, 'Vinte': 20, 'Trinta': 30}
dict2 = {'Trinta': 30, 'Quarenta': 40, 'Cinquenta': 50}
dicionario = dict1.copy()
dicionario.update(dict2)
print(dicionario)

Exercício 3- Faça um dicionário que armazene as seguintes informações cidade, latitude e longitude igual o exemplo abaixo.


>{'cidade' : 'Curitiba', 'latitude':-25.2548, 'longitude':-49.1615}

Leia algumas coordenadas de cidade digitadas pelo usuário e armazene em uma lista até que o usuário não preencha nada no local do nome.
Nesse momento descubra qual a cidade mais ao norte, sul, leste e oeste.

In [ ]:
#listas vazias que vão armazenar as informações
listaCidades= []
cidadeCoordenada = {}

#leitura da lista de cidades
nome = input('Digite uma cidade: ')
while nome != '' :
  cidadeCoordenada['cidade'] = nome
  cidadeCoordenada['latitude'] = float(input('Digite uma latitude: '))
  cidadeCoordenada['longitude'] = float(input('Digite uma longitude: '))
  listaCidades.append(cidadeCoordenada.copy())
  nome = input('Digite uma cidade: ')

#colocando em ordem crescente por latitude e longitude
listaNorteSul =   sorted(listaCidades,key=lambda dicionario: dicionario['latitude'])
listaLesteOeste = sorted(listaCidades,key=lambda dicionario: dicionario['longitude'])

#pegando o primeiro e o último elemento da lista para saber qual é a menor e maior longitude e latitude
norte = listaNorteSul[-1]
sul =   listaNorteSul[0]
leste = listaLesteOeste[-1]
oeste = listaLesteOeste[0]

print(f'A cidade mais ao norte é {norte["cidade"]} ')
print(f'A cidade mais ao sul é {sul["cidade"]} ')
print(f'A cidade mais ao leste é {leste["cidade"]} ')
print(f'A cidade mais ao oeste é {oeste["cidade"]} ')

Exercício 4- Peça para o usuário digitar uma frase. Na sequência diga quantas vezes cada palavra apareceu na frase.

In [ ]:
#frase = "a palavra dada dita por mim é igual a palavra dita por ele"
frase = input("Digite uma frase")

listaPalavras = frase.split(" ")

dicionario={}
for palavra in listaPalavras:
  dicionario[palavra]=dicionario.get(palavra,0)+1

for palavra,ocorrencias in dicionario.items() :
  print(palavra,':',ocorrencias,'vezes')